name: Create Pre-Release

on: 
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build & Create Release & Upload Asset
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            file: 'dist/pdf2pro6x.exe'
            asset: 'pdf2pro6x_win_x64.exe'
          - os: macos-latest
            file: 'dist/pdf2pro6x'
            asset: 'pdf2pro6x_mac_x64'
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Build project
        run: |
          pip install -r requirements.txt && pyinstaller -F pdf2pro6x.py && mv ${{ matrix.file }} ${{ matrix.asset }}
        shell: bash
      - name: Create Release & Upload binary
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          artifact: ${{ matrix.asset }}
