name: Create Pre-Release

on: 
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
jobs:
  build:
    name: Build & Create Release & Upload Asset
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            executable: 'dist/pdf2pro6x.exe'
            installer: 'target/pdf2pro6xSetup.exe'
            artifact1: 'pdf2pro6x_cli_win_x64.exe'
            artifact2: 'pdf2pro6x_win_x64_setup.exe'
          - os: macos-latest
            executable: 'dist/pdf2pro6x'
            installer: 'target/pdf2pro6x.dmg'
            artifact1: 'pdf2pro6x_cli_mac_x64'
            artifact2: 'pdf2pro6x_mac_x64.dmg'
    steps:
      - name: Install NSIS
        uses: crazy-max/ghaction-chocolatey@v1.1.0
        with:
          args: install nsis
        if: matrix.os == 'windows-latest'
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.5'
      - name: Build project
        run: |
          pip install -r requirements.txt && pyinstaller -F src/main/python/pdf2pro6x.py && mv ${{ matrix.executable }} ${{ matrix.artifact1 }} && fbs freeze && fbs installer && mv ${{ matrix.installer }} ${{ matrix.artifact2 }}
        shell: bash
      - name: Create Release & Upload binary
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          artifacts: ${{ matrix.artifact1 }}, ${{ matrix.artifact2 }}
