name: Create Pre-Release

on: 
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Create Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install Pipenv
        uses: VaultVulp/action-pipenv@v1.0.0
      - name: Build project on Mac
        if: matrix.os == 'macos-latest'
        run: |
          pipenv install --dev && pipenv run pyinstaller -F pdf2pro6x.py
      - name: Build project on Windows
        if: matrix.os == 'windows-latest'
        run: |
          pipenv install --dev -and pipenv run pyinstaller -F pdf2pro6x.py
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          prerelease: true
      - name: Upload Release Asset Windows
        if: matrix.os == 'windows-latest'
        id: upload-release-asset-windows
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./dist/pdf2pro6x.exe
          asset_name: pdf2pro6x_win_x64.exe
          asset_content_type: application/vnd.microsoft.portable-executable
      - name: Upload Release Asset macOS
        if: matrix.os == 'macos-latest'
        id: upload-release-asset-macos
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./dist/pdf2pro6x
          asset_name: pdf2pro6x_mac_x64
          asset_content_type: application/octet-stream
